[package]
name = "obrc-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.4"

[dev-dependencies]
iai = "0.1"
pretty_assertions = "1.4.0"
serde_json = "1.0.116"
serde = { version = "1.0", features = ["derive"] }

[[bench]]
name = "obrc"
harness = false
